import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { CustomLayout } from "@/components";
import { FONTS } from "@/app/fonts";
import React from "react";

export const metadata: Metadata = {
  title: "Scrap Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={FONTS.LATO.className}>
      {/*<Head>*/}
      {/*  <link*/}
      {/*    href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"*/}
      {/*    rel="stylesheet"*/}
      {/*  />*/}
      {/*</Head>*/}
      <body>
        <div id="root">
          <CustomLayout>{children}</CustomLayout>
        </div>
      </body>
    </html>
  );
}
