import type { Metadata } from "next";
import "./globals.css";
import { CustomLayout } from "@/components";
import { FONTS } from "@/app/fonts";
import React from "react";

export const metadata: Metadata = {
  title: "Scrap Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FONTS.LATO.variable}`}>
        <div id="root">
          <CustomLayout>{children}</CustomLayout>
        </div>
      </body>
    </html>
  );
}
