import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { CustomLayout } from "@/components";
import { FONTS } from "@/app/fonts";
import React from "react";
import Head from "next/head";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Scrap Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={FONTS.LATO.className}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>
        <ConfigProvider>
          <div id="root">
            <CustomLayout>{children}</CustomLayout>
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
